#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# virtualenvwrapper
export PROJECT_HOME="$HOME/projects"
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv

#export VIRTUAL_ENV_DISABLE_PROMPT=1
#export PYENV_ROOT=/usr/local/var/pyenv

export VELOCIRAPTOR_URL='https://deploy.yougov.net'
export VELOCIRAPTOR_AUTH_DOMAIN='deploy.yougov.net'

export ANSIBLE_HOSTS=~/ansible_hosts

# ruby
export PATH="/usr/local/opt/ruby/bin:$PATH"
# ensure that ruby gems scripts are installed in /usr/local/bin
# from https://coderwall.com/p/6bqzvq
if (( $+commands[brew] )) ; then
  brew_prefix="$(brew --prefix)"
  export RBENV_ROOT="$brew_prefix/opt/rbenv"
  export GEM_HOME="$brew_prefix/opt/gems"
  export GEM_PATH="$brew_prefix/opt/gems"
fi

# homebrew (generated via `brew shellenv`)
export HOMEBREW_PREFIX="/usr/local"
export HOMEBREW_CELLAR="/usr/local/Cellar"
export HOMEBREW_REPOSITORY="/usr/local/Homebrew"
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
export MANPATH="/usr/local/share/man:$MANPATH"
export INFOPATH="/usr/local/share/info:$INFOPATH"

# golang
export GOROOT="$(go env GOROOT)"
export GOPATH=$HOME/projects/defcon-workspace
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

# openssl
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/opt/openssl@1.1/lib"
